[tool.poetry]
name = "scrapping_and_post_libraries"
version = "0.1.0"
description = "Graph based, Hikerapi based Libraries, and other Scraping based libraries"
authors = ["MLSMIT <manuel.luis.sanchez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
facebook-sdk = "^3.1.0"
pandas = "^2.1.2"
numpy = "^2.0.0"
hikerapi = "^0.0.2"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
