[tool.poetry]
name = "scrapping-and-post-libraries"
version = "0.1.0"
description = "Graph based, Hikerapi based Libraries, and other Scraping based libraries"
authors = ["MLSMIT <manuel.luis.sanchez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
facebook-sdk = "^3.1.0"
pandas = "^2.1.2"
numpy = "^1.27.0"
hikerapi = "^0.0.2"
requests = "^2.32.3"
# fb-api = { path = "Graph API Libraries/fb-api" }
# ig-api = { path = "Graph API Libraries/ig-api" }
# th-api = { path = "Graph API Libraries/th-api" }
tt-api = { path = "Graph API Libraries/tt-api" }
x-api = { path = "Graph API Libraries/x-api" }
yt-api = { path = "Graph API Libraries/yt-api" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
