[tool.poetry]
name = "scrapping_and_post_libraries"
version = "0.1.0"
description = ""
authors = ["MLSMIT <manuel.luis.sanchez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.14"
hikerapi = "^0.0.2"
pandas = "^2.2.2"
numpy = "^1.26.4"
requests = "^2.32.3"


[tool.poetry.packages]
[tool.poetry.packages.fb-api]
include = "fb-api"
[tool.poetry.packages.ig-api]
include = "ig-api"
[tool.poetry.packages.shared-utils]
include = "shared-utils"
[tool.poetry.packages.th-api]
include = "th-api"
[tool.poetry.packages.tt-api]
include = "tt-api"
[tool.poetry.packages.yt-api]
include = "yt-api"
[tool.poetry.packages.x-api]
include = "x-api"
[tool.poetry.packages.main-app]
include = "main-app"
[tool.poetry.packages.tests]
include = "tests"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"